export const locationsData = [
  {
    countryCode: "at",
    countryName: "Austria",
    countryCities: [
      "Dornbirn",
      "Graz",
      "Innsbruck",
      "Klagenfurt",
      "Linz",
      "Salzburg",
      "Sankt Pölten",
      "Vienna",
      "Villach",
      "Wels",
    ],
  },
  {
    countryCode: "be",
    countryName: "Belgium",
    countryCities: [
      "Aalst",
      "Antwerp",
      "Bruges",
      "Brussels",
      "Ghent",
      "Leuven",
      "Liège",
      "Mechelen",
      "Mons",
      "Namur",
    ],
  },
  {
    countryCode: "bg",
    countryName: "Bulgaria",
    countryCities: [
      "Burgas",
      "Dobrich",
      "Pleven",
      "Plovdiv",
      "Ruse",
      "Shumen",
      "Sliven",
      "Sofia",
      "Stara Zagora",
      "Varna",
    ],
  },
  {
    countryCode: "hr",
    countryName: "Croatia",
    countryCities: [
      "Karlovac",
      "Osijek",
      "Pula",
      "Rijeka",
      "Sesvete",
      "Slavonski Brod",
      "Split",
      "Varaždin",
      "Zadar",
      "Zagreb",
    ],
  },
  {
    countryCode: "cy",
    countryName: "Cyprus",
    countryCities: [
      "Famagusta",
      "Kyrenia",
      "Larnaca",
      "Limassol",
      "Nicosia",
      "Paphos",
      "Paralimni",
      "Peyia",
      "Polis",
      "Protaras",
    ],
  },
  {
    countryCode: "cz",
    countryName: "Czech Republic",
    countryCities: [
      "Brno",
      "Hradec Králové",
      "Liberec",
      "Olomouc",
      "Ostrava",
      "Pardubice",
      "Plzeň",
      "Prague",
      "Ústí nad Labem",
      "Zlín",
    ],
  },
  {
    countryCode: "dk",
    countryName: "Denmark",
    countryCities: [
      "Aalborg",
      "Aarhus",
      "Copenhagen",
      "Esbjerg",
      "Horsens",
      "Kolding",
      "Odense",
      "Randers",
      "Roskilde",
      "Vejle",
    ],
  },
  {
    countryCode: "ee",
    countryName: "Estonia",
    countryCities: [
      "Kohtla-Järve",
      "Kuressaare",
      "Maardu",
      "Narva",
      "Pärnu",
      "Rakvere",
      "Sillamäe",
      "Tallinn",
      "Tartu",
      "Viljandi",
    ],
  },
  {
    countryCode: "fi",
    countryName: "Finland",
    countryCities: [
      "Espoo",
      "Helsinki",
      "Jyväskylä",
      "Kuopio",
      "Lahti",
      "Oulu",
      "Pori",
      "Tampere",
      "Turku",
      "Vantaa",
    ],
  },
  {
    countryCode: "fr",
    countryName: "France",
    countryCities: [
      "Bordeaux",
      "Lille",
      "Lyon",
      "Marseille",
      "Montpellier",
      "Nantes",
      "Nice",
      "Paris",
      "Strasbourg",
      "Toulouse",
    ],
  },
  {
    countryCode: "de",
    countryName: "Germany",
    countryCities: [
      "Berlin",
      "Cologne",
      "Dortmund",
      "Düsseldorf",
      "Essen",
      "Frankfurt",
      "Hamburg",
      "Leipzig",
      "Munich",
      "Stuttgart",
    ],
  },
  {
    countryCode: "gr",
    countryName: "Greece",
    countryCities: [
      "Athens",
      "Chania",
      "Heraklion",
      "Ioannina",
      "Kalamata",
      "Larissa",
      "Patras",
      "Rhodes",
      "Thessaloniki",
      "Volos",
    ],
  },
  {
    countryCode: "hu",
    countryName: "Hungary",
    countryCities: [
      "Budapest",
      "Debrecen",
      "Győr",
      "Kecskemét",
      "Miskolc",
      "Nyíregyháza",
      "Pécs",
      "Szeged",
      "Székesfehérvár",
      "Szombathely",
    ],
  },
  {
    countryCode: "ie",
    countryName: "Ireland",
    countryCities: [
      "Bray",
      "Cork",
      "Drogheda",
      "Dublin",
      "Dundalk",
      "Galway",
      "Limerick",
      "Navan",
      "Swords",
      "Waterford",
    ],
  },
  {
    countryCode: "it",
    countryName: "Italy",
    countryCities: [
      "Bari",
      "Bologna",
      "Catania",
      "Florence",
      "Genoa",
      "Milan",
      "Naples",
      "Palermo",
      "Rome",
      "Turin",
    ],
  },
  {
    countryCode: "lv",
    countryName: "Latvia",
    countryCities: [
      "Daugavpils",
      "Jēkabpils",
      "Jelgava",
      "Jūrmala",
      "Liepaja",
      "Ogre",
      "Rēzekne",
      "Riga",
      "Valmiera",
      "Ventspils",
    ],
  },
  {
    countryCode: "lt",
    countryName: "Lithuania",
    countryCities: [
      "Alytus",
      "Jonava",
      "Kaunas",
      "Klaipeda",
      "Mažeikiai",
      "Marijampolė",
      "Panevėžys",
      "Šiauliai",
      "Utena",
      "Vilnius",
    ],
  },
  {
    countryCode: "lu",
    countryName: "Luxembourg",
    countryCities: [
      "Diekirch",
      "Differdange",
      "Dudelange",
      "Esch-sur-Alzette",
      "Ettelbruck",
      "Grevenmacher",
      "Luxembourg City",
      "Remich",
      "Vianden",
      "Wiltz",
    ],
  },
  {
    countryCode: "mt",
    countryName: "Malta",
    countryCities: [
      "Birkirkara",
      "Fgura",
      "Marsaskala",
      "Mosta",
      "Qormi",
      "Rabat",
      "Sliema",
      "Valletta",
      "Żabbar",
      "Żejtun",
    ],
  },
  {
    countryCode: "nl",
    countryName: "Netherlands",
    countryCities: [
      "Almere",
      "Amsterdam",
      "Breda",
      "Eindhoven",
      "Groningen",
      "Nijmegen",
      "Rotterdam",
      "The Hague",
      "Tilburg",
      "Utrecht",
    ],
  },
  {
    countryCode: "pl",
    countryName: "Poland",
    countryCities: [
      "Bydgoszcz",
      "Gdańsk",
      "Katowice",
      "Krakow",
      "Lublin",
      "Łódź",
      "Poznań",
      "Szczecin",
      "Warsaw",
      "Wroclaw",
    ],
  },
  {
    countryCode: "pt",
    countryName: "Portugal",
    countryCities: [
      "Almada",
      "Amadora",
      "Braga",
      "Coimbra",
      "Funchal",
      "Lisbon",
      "Matosinhos",
      "Porto",
      "Setúbal",
      "Vila Nova de Gaia",
    ],
  },
  {
    countryCode: "ro",
    countryName: "Romania",
    countryCities: [
      "Brașov",
      "Bucharest",
      "Cluj-Napoca",
      "Constanța",
      "Craiova",
      "Galați",
      "Iași",
      "Oradea",
      "Ploiești",
      "Timișoara",
    ],
  },
  {
    countryCode: "sk",
    countryName: "Slovakia",
    countryCities: [
      "Banská Bystrica",
      "Bratislava",
      "Košice",
      "Martin",
      "Nitra",
      "Poprad",
      "Prešov",
      "Trenčín",
      "Trnava",
      "Žilina",
    ],
  },
  {
    countryCode: "si",
    countryName: "Slovenia",
    countryCities: [
      "Celje",
      "Koper",
      "Kranj",
      "Ljubljana",
      "Maribor",
      "Murska Sobota",
      "Novo Mesto",
      "Ptuj",
      "Velenje",
      "Vršac",
    ],
  },
  {
    countryCode: "es",
    countryName: "Spain",
    countryCities: [
      "Alicante",
      "Barcelona",
      "Bilbao",
      "Granada",
      "Madrid",
      "Malaga",
      "Murcia",
      "Seville",
      "Valencia",
      "Zaragoza",
    ],
  },
  {
    countryCode: "se",
    countryName: "Sweden",
    countryCities: [
      "Gothenburg",
      "Helsingborg",
      "Jönköping",
      "Linköping",
      "Lund",
      "Malmö",
      "Stockholm",
      "Uppsala",
      "Västerås",
      "Örebro",
    ],
  },
  {
    countryCode: "gb",
    countryName: "United Kingdom",
    countryCities: [
      "Birmingham",
      "Bristol",
      "Cardiff",
      "Edinburgh",
      "Glasgow",
      "Leeds",
      "Liverpool",
      "London",
      "Manchester",
      "Newcastle",
    ],
  },
];
