// src/models/Repayment.js
import mongoose from "mongoose";
import HistorySubSchema from "./HistorySubSchema.js";

const repaymentSchema = new mongoose.Schema(
  {
    investment: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Investment",
      required: true,         // Link back to the investment
    },
    venture: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Venture",
      required: true,         // Redundant but handy for lookups
    },
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,         // Who paid this repayment
    },

    amount:         { type: Number, required: true },      // Paid this cycle
    expectedAmount: { type: Number },                      // What was due
    type: {
      type: String,
      enum: ["principal", "profit"],
      required: true,         // Repayment category
    },
    date: { type: Date, default: Date.now },               // When paid

    status: {
      type: String,
      enum: ["pending", "paid", "rejected"],
      default: "pending",
      index: true,           // Fast queries by payment state
    },

    scheduleIndex:    { type: Number },                    // Which installment
    proofImage:       { type: String },                    // Receipt or proof
    isAutoGenerated:  { type: Boolean, default: false },   // System-created?

    source: {
      type: String,
      enum: ["manual", "system", "cron"],
      default: "manual",     // Origin of this record
    },

    // ─── Change History ─────────────────────────────────────────────────────
    history: [HistorySubSchema],   // Logs of status changes, corrections, etc.

  },
  { timestamps: true }            // createdAt, updatedAt
);

export default mongoose.model("Repayment", repaymentSchema);
