// src/models/Repayment.js
import mongoose from "mongoose";

const repaymentSchema = new mongoose.Schema(
  {
    investment: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Investment",
      required: true,
      index: true,
    },
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    amount: { type: Number, required: true },
    type: {
      type: String,
      enum: ["principal", "profit"],
      required: true,
    },
    date: { type: Date, default: Date.now },
    status: {
      type: String,
      enum: ["pending", "paid", "rejected"],
      default: "pending",
      index: true,
    },

    note: { type: String },
    proofImage: { type: String },
    scheduleIndex: { type: Number },
    isAutoGenerated: { type: Boolean, default: false },
    expectedAmount: { type: Number },
    source: {
      type: String,
      enum: ["manual", "system", "cron"],
      default: "manual",
    },
    venture: { type: mongoose.Schema.Types.ObjectId, ref: "Venture" },
    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    approvedBy: { type: mongoose.Schema.ObjectId, ref: "User" },
    approvedAt: { type: Date },
  },
  { timestamps: true }
);

export default mongoose.model("Repayment", repaymentSchema);
